# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: "Intuitive Counter: A Blog about Scala, Graphs, and Coding"
email: david@walend.net
description: "David Walend's blog about scala, graphs, and coding"
baseurl: "/blog"
url: "http://dwalend.github.io"
twitter_username: dwalend
github_username: dwalend

# Build settings
markdown: kramdown

